### ISSUE TITLE
k3d release v5.0.0 changes parameters server-args and needs adaption of kyma cli.

### ISSUE THREAD

**Issue by johgoe** [kyma-project/cli#1017]
Just saw that k3d.io has a new major release 5.0.0, which includes a dns refactoring. 

Now it's possible to use the k3d-registry (see #805) 

Please note that release 5.0.0 changes the parametes ` --k3s-server-arg --no-deploy --k3s-server-arg traefik` to `--k3s-arg "--no-deploy=traefik@server:0"` which also affects the kyma cli.

My working test setup on windows 11 with wsl with a kyma v.1.24.6 and a serverless override configuration use the following commands.

```
k3d registry create registry.localhost -p 5000

k3d cluster create kyma \
    --image docker.io/rancher/k3s:v1.19.11-k3s1 \
    --port 80:80@loadbalancer \
    --port 443:443@loadbalancer \
    --agents 1 \
    --k3s-arg "--no-deploy=traefik@server:0" \
    --network kyma \
    --registry-use k3d-registry.localhost:5000 \
    --wait \
    --timeout 60s
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: serverless-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: serverless
    kyma-project.io/installation: ""
data:
  webhook.values.buildJob.resources.defaultPreset: "local-dev"
  dockerRegistry.enableInternal: "false"
  dockerRegistry.serverAddress: "k3d-registry.localhost:5000"
  dockerRegistry.registryAddress: "k3d-registry.localhost:5000"
  tests.enabled: "false"
```
