### ISSUE TITLE
Function ENVS are not injected properly when running a function locally via kyma CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#1112]
**Description**

Function ENVS are not properly injected when running a function in a local docker runtime

**Expected result**

Function ENVS should be properly injected and resolvable in the handler when running a function locally via kyma CLI

**Actual result**

Function ENVS are not injected properly when running a function locally via kyma CLI

**Steps to reproduce**

1. Run `kyma init function` in an empty folder
2. Define `config.yaml` and `handler.js` as attached
3. Run function locally via `kyma run function --hot-deploy`
4. Observe that `process.env[]` are resolved to undefined 

Same function works fine when deployed to kyma runtime.

**Attachments**

 - sample manifest
 
 ```
name: my-function
namespace: dev
runtime: nodejs14
source:
  sourceType: inline
  sourceHandlerName: handler.js
  depsHandlerName: package.json
env:
  - name: MICROSERVICE_SERVICE_HOST
    value: localhost
  - name: MICROSERVICE_SERVICE_PORT
    value: '3000'
 ```
  - sample handler
  
```
module.exports = {
    main: function (event, context) {
        console.log("Host",process.env['MICROSERVICE_SERVICE_HOST'])
        console.log("Port",process.env['MICROSERVICE_SERVICE_PORT'])
        return 'Hello Serverless'
    }
} 
```
