### ISSUE TITLE
Adapt Kyma CLI function commands to the new CRD versions

### ISSUE THREAD

**Issue by Cortey** [kyma-project/cli#1314]
**Description**

We want to adapt kyma CLI function commands  to the recently released CRD versions:
 - serverless.kyma-project.io/v1alpha2
 - gateway.kyma-project.io/v1beta1
 
**AC**
 - [x] `kyma apply function` should render functions and api-rules specs according to the new versions
 - [x] `kyma sync function` should be able to read functions and api-rules in the new versions and transfor into config.yaml manifest
 - [ ] resource information is included - https://github.com/kyma-project/cli/issues/1378

**Note**
Make sure to fit into the backward compatibility contract

**Related**
Main story: https://github.com/kyma-project/kyma/issues/14593

**Comment by kwiatekus** [comment]
I think the changes around APIRules are buggy

When synchronising a following function from kyma on k3d  into the local workspace via `kyma sync` command I see that api rule service is empty

![Screenshot 2022-11-10 at 14 18 39](https://user-images.githubusercontent.com/6783567/201102572-2dc4d253-2b0b-4464-aaba-f25ca34d9b01.png)


```yaml
name: fun-node16-2
namespace: default
labels:
    app.kubernetes.io/name: fun-node16-2
runtime: nodejs16
source:
    sourceType: inline
    sourcePath: /tmp/synced
subscriptions:
    - name: fun-node16-meaty-inspector-2
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.kyma.order.cancelled.v1
env:
    - name: foo
      value: bar
    - name: sadasd
      valueFrom:
        configMapKeyRef:
            name: crds-status
            key: name
apiRules:
    - service:
        host: ""
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow
```

The structures in the CLI are not reflecting the proper spec of API rule in version beta1
The host is on root level in the spec:

```yaml
- apiVersion: gateway.kyma-project.io/v1beta1
  kind: APIRule
  metadata:
    creationTimestamp: "2022-11-10T07:48:39Z"
    generation: 1
    name: fun-node16
    namespace: default
    ownerReferences:
    - apiVersion: serverless.kyma-project.io/v1alpha1
      kind: Function
      name: fun-node16
      uid: 2d608539-2e96-4a54-8453-21147b0216c5
    resourceVersion: "1665"
    uid: eea87bc8-6df8-4499-a8c7-9fd3109e0bac
  spec:
    gateway: kyma-gateway.kyma-system.svc.cluster.local
    host: fun-node16
    rules:
    - accessStrategies:
      - handler: allow
      methods:
      - GET
      path: /.*
    service:
      name: fun-node16
      port: 80
  status:
    APIRuleStatus:
      code: OK
    accessRuleStatus:
      code: OK
    lastProcessedTime: "2022-11-10T07:48:39Z"
    observedGeneration: 1
    virtualServiceStatus:
      code: OK
```

**Comment by kwiatekus** [comment]
Synchronising function from runtime to the workspace breaks the source content for inline functions:

I.e
 - apply the function

```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: aaaa
    name: aaaa
    namespace: default
spec:
    runtime: nodejs16
    source:
        inline:
            dependencies: |-
                {
                  "name": "fun-node16",
                  "version": "0.0.1",
                  "dependencies": {}
                }
            source: |-
                module.exports = {
                    main: function (event, context) {
                        return 'Hello Serverless'
                    }
                }
```

 - sync the function
`kyma-dev sync function aaaa`
The content of the `handler.js` contains the function name not the actual function code
