### ISSUE TITLE
Update config.yaml schema to reflect v1alpha2 Subscription api

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#1532]
**Description**

Kyma CLI should reflect new subscription API in the schema of config.yaml

 - [ ] introduce versioning of config.yaml schema
 - [ ] do not break compatibility with the previous version of schema. 
 - [ ] user can apply previous content (and see depreciation warning)
 - [ ] user can apply new content that reflects new subscription API
 - [ ] when no version is defined in the config.yaml, the previous schema is used and previous API is used to apply subscriptions.
 

**Reasons**
Soon eventing module will release a [new api version for Subscription CRD](https://github.com/kyma-project/kyma/blob/98e0fb4f6fa719f1df7a5a2c6d16cb5da982cfd8/components/eventing-controller/config/crd/basesv1alpha2/eventing.kyma-project.io_subscriptions.yaml). 
Kyma CLI and the types in hydroform should catch up so that users can use the same data structures in function configuration file that is applied via kyma CLI

**Related**
https://github.com/kyma-project/kyma/issues/16631

**Attachments**
Samples:
1) previous schema is used when no version is given. This will still work for users and cli will warn them when applying the content

```yaml
name: event-receiver
namespace: default
runtime: nodejs16
source:
   sourceType: inline
subscriptions:
   - name: event-receiver
     protocol: ""
     filer:
        filters:
           - eventSource:
               property: source
               type: exact
               value: ""
            eventType:
               property: type
               type: exact
               value: sap.kyma.custom.acme.payload.sanitised.v1
```
2) New subscription API is used when `schemaVersion` is given

```yaml
schemaVersion: v1 //<-- versioning
name: event-receiver
namespace: default
runtime: nodejs16
source:
   sourceType: inline
subscriptions:
  - name: event-receiver
     sink: http://test.tunas-testing.svc.cluster.local/
     source: ""
     typeMatching: exact
     types:
      - sap.kyma.custom.noapp.order.created.v1
      - sap.kyma.custom.test-app.order.created.v1
```
