### ISSUE TITLE
Module template created with kyma CLI cannot be installed

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/cli#1543]
**Description**
The module template created with the latest Kyma CLI is not installable with lifecycle-manager. 
The CRD is not installed even. Can't find any meaningful information about the actual problem in the lifecycle-manager logs. The only error message I found is in the Manifest resource:
```
   lastOperation:
      lastUpdateTime: "2023-02-17T14:22:21Z"
      operation: 'Get "https://https/v2/": dial tcp: lookup https on 10.96.0.10:53:
        no such host'
    state: Error
```

**Expected result**
Operator is installed or at least meaningful error is reported.

**Actual result**

Error state of Kyma.

**Steps to reproduce**
Just follow this interactive tutorial:
https://killercoda.com/kyma-project/scenario/cluster-ip

Module template:
https://github.com/pbochynski/cluster-ip/blob/main/cluster-ip-module-template.yaml

The operator repository:
https://github.com/pbochynski/cluster-ip

Command used to create module template:
https://github.com/pbochynski/cluster-ip/blob/e8ec96e0ab104cc1569236ffbfd72e1def454a7b/manual-release.sh#L8-L10
