### ISSUE TITLE
kyma disable module command can't handle module use global channel

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1576]
**Description**

in disable module command, if module defined in kyma use global level channel,
```
spec:
    channel: alpha
    modules:
    - customResourcePolicy: CreateAndDelete
      name: keda
```

**Expected result**

 the disable command use channel flag should possible disable modules which defined in global level channel

**Actual result**

the disable command use channel flag will report not found error:
```
kyma alpha disable module keda -c alpha -n kcp-system -k default-kyma
```
```
Error: could not disable module as it was not found: keda in channel alpha
```
**Steps to reproduce**

**Troubleshooting**
