### ISSUE TITLE
Pass sources description in the metadata file for create module command

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1724]
**Description**

It should be possible to pass `sources` information in the metadata file that is used to create the module. It should be later used in the descriptor of the ModuleTemplate.

Previously CLI inherited sources information from the Kubebuilder project. With that way of building modules gone, we would need some replacement for filling that part of the ModuleTemplate.

The example of the section is (from Keda manager):
```
sources:
      - access:
          commit: 12b17206592c2cee36885e3833f1edac04a6ad1c
          repoUrl: github.com/kyma-project/keda-manager
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/v0.3.1
          version: v1
        - name: scan.security.kyma-project.io/language
          value: golang-mod
          version: v1
        - name: scan.security.kyma-project.io/subprojects
          value: "false"
          version: v1
        - name: scan.security.kyma-project.io/exclude
          value: '**/test/**,**/*_test.go'
          version: v1
        name: module-sources
        type: git
        version: v0.3.1
```

As this section is built out of git information and sec-scanners config file we would need to find a way to somehow collect that information and merge it in the final output. (See: https://github.com/kyma-project/keda-manager/blob/main/sec-scanners-config.yaml)

We can think of either:
- passing it in metadata.yaml file used for building modules
- using a separate file and referencing it in the metadata.yaml

**Acceptance Criteria**

- [ ] It is possible to pass `sources` information in the metadata yaml used for creating the module
- [ ] The sources section of the ModuleTemplate contains security scanner config for the sources
