### ISSUE TITLE
Security scanner config not being used in the kubebuilder create module version

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1745]
**Description**

Security scanner configuration is not propagated with the `--kubebuilder-project` parameter passed.

**Expected result**

Security scanner config incorporated in the ModuleTemplate

**Actual result**

All the security information is filled in the ModuleTemplate.

**Steps to reproduce**

```
kyma-unstable alpha create module --kubebuilder-project --sec-scanners-config module_scanners_config.yaml --channel=alpha --name kyma.project.io/module/btp-operator --version 0.5.0 --path . --registry europe-docker.pkg.dev/kyma-project/prod/unsigned -c oauth2accesstoken:
```

See: https://github.tools.sap/kyma/kyma-modules/pull/153/files
Repository used: https://github.com/kyma-project/btp-manager
Security scanner config: https://github.com/kyma-project/btp-manager/blob/main/sec-scanners-config.yaml

**Comment by jaroslaw-pieszka** [comment]
Security file used while invoking `kyma`
```
module-name: btp-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.5.0
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
```
