### ISSUE TITLE
Kyma CLI `module create` command has to consider new fields in security configuration file

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1755]
**Description**

Caused by changing requirements on the security backend side of Kyma, following new fields (which are both not related to one of the scanners) were added to the Kyma security configuration file:

* `/dev-branch` (type: string)
* `/rc-tag` (type: string)
(Should be added as labels in sources)

This field was removed in the meantime:
*  `/whitsource/subprojects` (type: boolean)

Summary/Example of security config file:
```
module-name: btp-operator
rc-tag: 0.5.0.           #<< new field
dev-branch: main.        #<< new field
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.5.0
whitesource:
  language: golang-mod
  subprojects: false     #<<< This field is no longer used!
  exclude:
    - "**/*_test.go"
```
Exmaple of rendered moduletemplate:
```
     - access:
          commit: abcd1234
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        - name: scan.security.kyma-project.io/language
          value: golang-mod
          version: v1
        - name: scan.security.kyma-project.io/dev-branch
          value: main
          version: v1
        - name: scan.security.kyma-project.io/rc-tag
          value: 0.5.0
          version: v1
        - name: scan.security.kyma-project.io/exclude
          value: '**/test/**'
          version: v1
```

The rendering of Kyma module templates should consider these changes and remove the dropped fields but also add the new fields.

AC:
- [x] New added fields (see above) in Kyma security file are added to the generated Kyma module template
- [x] Removed fields (see above) in Kyma security file are not longer added to the generated Kyma module template
