### ISSUE TITLE
The RepoUrl is not set correctly when running the alpha create module

### ISSUE THREAD

**Issue by medmes** [kyma-project/cli#1760]
**Description**

The current command alpha create module, when sources are added to the image layer. It use the current repo url  for the sources. Instead of the target git directory.

**Expected result**

The command should set the repoUrl attribute to the target git repository url.

**Actual result**
The command set the repoUrl attribute to the current git repository url (e.g: https://github.com/medmes/cli) if the command is ran under cli project.

**Steps to reproduce**

` ./bin/kyma-darwin alpha create module --module-config-file=./config.yaml -p [--path-to-git-project-directory]  --registry k3d-registry.localhost:5111 --insecure`

check the generated `template.yaml` in the sources section:
```yaml
sources:
      - access:
          commit: d7afd3e0d727622df0b99bab27c311720bd4ad2f
          repoUrl: https://github.com/medmes/cli
          type: gitHub
```
**Solutiion**

In the `inspectProject function, the def.Repo = p.Repo` should be removed.
https://github.com/kyma-project/cli/blob/f79fdabdea730d5bae47c0205a4a6f7b474c40d5/pkg
