### ISSUE TITLE
Wrong repoUrl in moduletemplate.yaml in parent-child git structure

### ISSUE THREAD

**Issue by the1bit** [kyma-project/cli#1765]
**Description**

In our use case we execute the `kyma alpha create module` command in a parent-child structure with 2 cloned Git repository.
```bash
(parent-git-code)
├── modules
├── child-git-code
```
1st Git related code (parent git-code): Pipeline related code.
2nd Git related code (child git-code): Kyma module related code

When we run the `kyma alpha create module` command from the `parent-git-code` directory and define the `child-git-code` relative path for kyma-cli command the generated module template contains the `parent` Git URL instead of `child` Git URL.

Related lines on this way:
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma/parent-repo
```

Expected lines:
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma-project/child-repo
```

Command we use:
```bash
kyma alpha create module \
                  --module-config-file ./child-git-code/config.yaml \
                  --path ./child-git-code \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```

**Version**: We used the unstable version which was available at 2023-09-12 08:00:00 CEST.
**OS**: Ubuntu 22.04 - Azure Pipeline

**Expected result**

moduletemplate.yaml
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma-project/child-repo
```
**Actual result**

moduletemplate.yaml
```yaml
      - access:
          commit: 21**************
          repoUrl: https://github.****/kyma/parent-repo
```
**Steps to reproduce**

1. Clone a git repository as `parent` repository
2. Enter the cloned repository directory
3. Clone the Kyma module git repository as `child`
4. Execute the kyma-cli command in parent directory

```bash
kyma alpha create module \
                  --module-config-file ./child/config.yaml \
                  --path ./child \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```

**Troubleshooting**

Modify our code and run it from `child` directory
```bash
cd child

kyma alpha create module \
                  --module-config-file ./config.yaml \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```
