### ISSUE TITLE
CLI is still requiring access to the Github repository of a Kyma module to be able to build the module template

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1781]
**Description**
During the execution of the submission build pipeline is still access to the Github repository of the KYma module required. This causes issues during the submissions pipeline execution in cases that the repository is not public accessible (e.g. SAP internal Github repository is only reachable via VPN).

It was agreed that the KYma CLI should use only the information provided in the Kyma module configuration file for building the module template. It should not need access to the Kyma module repository.

**Expected result**

Kyma CLI is not requiring access to the Kyma module repository and is able to create the module template file by using only the information provided in the module configuration file.

**Actual result**

Kyma CLI is connecting to the Kyma module repository .

**Steps to reproduce**

See currently failing pipeline: https://dev.azure.com/hyperspace-pipelines/kyma/_build/results?buildId=2982297&view=results

**Troubleshooting**

**Comment by ruanxin** [comment]
The only reason that CLI need module repo information is because of the security scan info required by neighbours.
CLI need to know this module repo `commit` hash, `repoUrl` to build the access layer. At the moment, CLI automatically get it from reading `.git` folder, that's why it needs to clone the module repo first.

look at the example:
```
      sources:
      - access:
          commit: b6eff18920cd00b8c98a35f8bba0d196a8c95e40
          repoUrl: github.com/kyma-project/keda-manager
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        - name: scan.security.kyma-project.io/language
          value: golang-mod
          version: v1
        - name: scan.security.kyma-project.io/subprojects
          value: "false"
          version: v1
        - name: scan.security.kyma-project.io/exclude
          value: /test
          version: v1
        name: module-sources
        type: git
        version: v0.1.0-b6eff18
      version: v0.1.0-b6eff18
```
I see two options here:
1. If security scan info is not required in the final module template, then CLI already have this feature to ignore it during module creation.
2. If not, then repo `commit` hash, `repoUrl` should be manually provided by module team, this can be some additional fields in module-config file. But then this should be aligned with each module team. @tobiscr, this process should be initiated by your team.

If have any other ideas, feel free to write here.
