### ISSUE TITLE
Support for `customStateCheck` field in create module command

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1784]
**Description**

There should be an option to pass the configuration for the [custom state check functionality](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md#speccustomstatecheck) of the Module Templates.

A proper section should be added to the yaml file referenced with the `--module-config-file` flag. It can have a 1:1 structure with what is present in the Module Template:
```
customStateCheck:
  - jsonPath: 'status.health'
    value: 'green'
    mappedState: 'Ready'
  - jsonPath: 'status.health'
    value: 'red'
    mappedState: 'Error'
```

or for the complex mapping:
```
customStateCheck:
  - jsonPath: 'module.state.field1'
    value: 'value1'
    mappedState: 'Ready'
  - jsonPath: 'module.state.field2'
    value: 'value2'
    mappedState: 'Ready'
```

**Reasons**

We want to provide support for all the possible fields in Module Template CR for building modules with the command.

**Acceptance Criteria**
- [ ] Provide a way to configure custom state check in `kyma alpha create module` command
