### ISSUE TITLE
Allow referencing shared service instances via kyma CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#1997]
**Description**
Kyma cli should make it easy to create 'reference-instance' that references already existing service instances.
This way users get an open path to binding to existing instances and also deleting kyma environment w/o the need to remove all phisically provisioned service instances

**Execution**
 - [x] try it out manually in btp (creating shared service instance and reference it ( and bind ) in kyma runtime) (1)
 - [x] implement a command that would take service offering name and shared instance name to create a reference service instance

**Reason**
Kyma CLI should enable users an effortless binding of service instances that were already created and marked as "shared"
Cases for instance sharing:
 - An application may consist of multiple microservices running on different platforms. Sharing the same RabbitMQ service instance would allow pubsub communication between those microservices. They can also share the same Postgresql service instance if needed.
 - The application can be moved to a different platform and still use the same service instances that it previously used.

**Attachment**
https://www.youtube.com/watch?v=AYULBewzEwI
https://help.sap.com/docs/btp/btp-cli-command-reference/btp-share-services-instance
https://wiki.one.int.sap/wiki/display/CPC15N/%5BCookbook%5D+Service+Instance+Sharing

**Comment by kwiatekus** [comment]
A target service instance must be "shared" <-- for now we treat this as a prerequisite, i.e user must share it via btp cockpit or [btp cli](https://help.sap.com/docs/btp/btp-cli-command-reference/btp-share-services-instance)

![Image](https://github.com/orgs/kyma-project/projects/26/assets/6783567/3d663475-358b-4740-80f0-8d0a4e1431a4)

A kyma cli command to reference a shared instance in  kyma runtime should create a **service instance** k8s resource  (taking service offering name, and name of the shared instance from user input). It should use fixed ` reference-instance` plan name 

```yaml
spec:
  externalName: object-store-ref
  parameters:
    referenced_instance_id: ''
    selectors:
      instance_label_selector: []
      instance_name_selector: object-store-cf
      plan_name_selector: ''
  serviceOfferingName: objectstore
  servicePlanName: reference-instance
```

and **service binding**
