### ISSUE TITLE
POC: Check how to pass hana db initialisation config when provisioning btp hana service instance

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#1999]
**Description**

Allow automating hana db initialization (schema, tables etc) via kyma cli.

Exemplary flow:
1) [kyma provision](https://github.com/kyma-project/cli/issues/1963)
2) [create hana instance & bind it ](https://github.com/kyma-project/cli/issues/1980)
3) **initialize hana via hana hdi containers**

Execute the flow manually and document findings as a comment in the issue.
Propose how should we approach this in the Kyma CLI?

**Reasons**

This feature is required for fully automated  deployments for apps  relying  on hana cloud db instance.

**Attachments**

Example app and the necessary [manual step](https://github.com/kwiatekus/kyma-demo/blob/main/README.md?plain=1#L23) that should be avoided
[hana cloud hdi instantiation in kyma](https://help.sap.com/docs/hana-cloud/sap-hana-cloud-getting-started-guide/set-up-hdi-container-kyma?locale=en-US)
[Manual](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-developer-guide-for-cloud-foundry-multitarget-applications-sap-business-app-studio/defining-data-model-in-sap-hana-cloud)
[Example configuration](https://github.tools.sap/fp-stakeholder-management/hana-cloud/tree/main/kyma-easy/faas/kyma-fun/kyma/helm/faas-db)

**Comment by halamix2** [comment]
1. `go run . provision --credentials-path cis_local.json --plan aws --region eu-central-1 --owner email @ email.com`
2. `go run . hana provision --kubeconfig kubeconfig.yaml --name hana`
3. Add entitlement `hana-cloud` -> `admin-api-access` & add its instance & binding
```yaml
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: hania-api
  labels:
    app.kubernetes.io/name: hania-api
  annotations: {}
  namespace: default
spec:
  serviceOfferingName: hana-cloud
  servicePlanName: admin-api-access
  parameters:
    technicalUser: true
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: hania-api
  labels:
    app.kubernetes.io/name: hania-api
  annotations: {}
  namespace: default
spec:
  serviceInstanceName: hania-api
  secretName: hania-api
```
4. Read the `baseurl` and `uaa` fields from the `baseurl` binding secret
5. Call POST `${uaa.url}/oauth/token` with basic auth of `uaa.clientid` / `uaa.clientsecret` and url-encoded body `grant_type=client_credentials`; get `access_token`
6. Get Kyma cluster ID: `kubectl get configmap sap-btp-operator-config -n kyma-system -o jsonpath='{.data.CLUSTER_ID}'`
7. Call POST `${baseurl}/inventory/v2/serviceInstances/${hana_instance_guid}/instanceMappings` with `access_token` as Bearer token and following  body:
```json
{
  "platform": "kubernetes",
  "primaryID": "<kyma_id>"
}
```
8. **initialize hana via hana hdi containers**
    - In Kyma create Hana instance in the default namespace
        - Service Management -> Service Instances -> Create
        - offering name - `hana`, plan name - `hdi-shared`
        ```yaml
        apiVersion: services.cloud.sap.com/v1
        kind: ServiceInstance
        metadata:
          name: hdi
          labels:
            app.kubernetes.io/name: hdi
          annotations: {}
          namespace: default
        spec:
          serviceOfferingName: hana
          servicePlanName: hdi-shared
        ```
