### ISSUE TITLE
Redefine the extensions concepts API

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/cli#2428]
**Description**

[The extensions concept](https://github.com/kyma-project/cli/issues/2221#issuecomment-2404978066) has a few early adoption problems:

* the `kyma-cli/extension: resource` label is confusing and not describe the goal of the functionality
* extension configuration is split into a few keys in the configmap (rootCommand, templateCommands, coreCommands, ...) and this is limiting and not easy to maintain
* extension sub-commands are split between three groups (templateCommands, coreCommands and customCommands) with different API and configuration methods
* the whole solution is code-complicating and hard to document

# V4

My proposition is improving this area and liquidating differences between sub-commands configurations. This proopsition also contains changes proposed in [this ticket](https://github.com/kyma-project/cli/issues/2425).

**Configmap**

Configmap now has new label value and one data record:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: serverless.function.cli
  namespace: kyma-system
  labels:
    kyma-cli/extension: commands
    kyma-cli/extension-version: v1
data:
  kyma-commands.yaml: |
    ...
```

## The `command` yaml

Another change is in the extension schema that contains one generic list of sub-commands (`subCommands` field):

```yaml
metadata:
  name: ...
  description: ...
  descriptionLong: ...
uses: ...
flags: []
args: ...
with: {}
subCommands: []
```

the `command` objects fields:

* `.metadata` - contains name and description
* `.uses` - name/id of the template to build command
* `.with` - config passed to command and merged with all subcommands config
* `.flags` - definition of additional flags that will overwrite/add fields to the config
* `.args` - definition of command argument that will overwrite/add fields to the config
* `.subCommands` - list of additional subcommands ( list of `command` objects )

Example of not operations command-group (without uses) and with subcommands:

```yaml
with: {}
metadata:
  name: ...
  description: ...
  descriptionLong: ...
subCommands:
- metadata:
    name: ...
    description: ...
    descriptionLong: ...
  uses: ...
  args:
    type: ...
    optional: ...
    configPath: ...
  flags:
  - name: ...
    configPath: ...
    type: ...
    description: ...
    default: ...
    required: ...
  with: {}
```

Process of composing command:

1. use `.metadata` to add name and descriptions
2. use `.uses` to add action run on command execution
3. add flags based on the `.flags`
4. add args based on the `.args`
4. compose and add all subcommands

When one of the commands is executed from the terminal, cli will:

1. merge `.with` with the config from the command above into one config
2. run flags&args and add their values to the config from point 1
3. execute commands action with the given config

## Conclusion

The new concept allows users to build any command trees that are running previously prepared scripts and configure them using flags or constant configuration defined in the cm.

## Examples

**Example of not operational (without uses) commands group containing a few operational subcommands (with uses):**

```yaml
with:
  resourceInfo:
    scope: namespace
    kind: Function
    version: v1alpha2
    group: serverless.kyma-project.io
metadata:
  name: function
subCommands:
- metadata:
    name: create
  uses: resource_create
- metadata:
    name: init
  uses: function_init
```

Commands tree:

```text
-- function # has no uses (help will be printed on the run)
    - create
    - init
```

**Example of fully operational command with subcommands of subcommands**

```yaml
metadata:
  name: function
uses: resource_explain
subCommands:
- metadata:
    name: create
  uses: resource_create
  subCommands:
  - metadata:
      name: demo
    uses: function_demo
```

Commands tree:

```text
-- function
    - create
      - demo
```

## Serverless extension yaml

```yaml
with:
  resource:
    apiVersion: serverless.kyma-project.io/v1alpha2
    kind: Function
metadata:
  name: function
  description: A set of commands for managing Functions
  descriptionLong: Use this command to manage Functions.

subCommands:
- metadata:
    name: "get [<resource_name>] [flags]"
    description: "Get Functions"
    descriptionLong: "Use this command to get Functions from a cluster."
  uses: resource_get
  args:
    type: string
    optional: true
    configPath: ".resource.metadata.name"
  flags:
  - type: string
    name: "namespace"
    shorthand: "n"
    description: "Function's namespace"
    configPath: ".resource.metadata.namespace"
    default: "default"
  - type: bool
    name: "all-namespaces"
    shorthand: "A"
    configPath: ".fromAllNamespaces"
    default: false
  with:
    outputParameters:
    - resourcePath: '.status.conditions[] | select(.type=="ConfigurationReady") | .status'
      name: "configured"
    - resourcePath: '.status.conditions[] | select(.type=="BuildReady") | .status'
      name: "built"
    - resourcePath: '.status.conditions[] | select(.type=="Running") | .status'
      name: "running"
    - resourcePath: ".spec.runtime"
      name: "runtime"
    - resourcePath: ".metadata.generation"
      name: "generation"

- metadata:
    name: "explain [flags]"
    description: "Explain Functions"
    descriptionLong: "Use this command to explain what Function is."
  uses: resource_explain
  with:
    output: |
      With Functions you can run code without
      writing servers and maintaining them. 
      
      There are two possible runtime variants: Node.js and Python.

      You can find more details here:
      https://kyma-project.io/#/serverless-manager/user/resources/06-10-function-cr

- metadata:
    name: "delete <resource_name> [flags]"
    description: "Delete Function"
    descriptionLong: "Use this command to delete Function from a cluster."
  uses: resource_delete
  args:
    type: string
    configPath: ".resource.metadata.name"
  flags:
  - type: string
    name: "namespace"
    shorthand: "n"
    description: "Function's namespace"
    configPath: ".resource.metadata.namespace"
    default: "default"

- metadata:
    name: "create <resource_name> [flags]"
    description: "Create Function"
    descriptionLong: "Use this command to create Function on a cluster."
  uses: resource_create
  args:
    type: string
    configPath: ".resource.metadata.name"
  flags:
  - type: string
    name: "runtime-image-override"
    description: "custom runtime image to be used as Function's runtime base"
    configPath: ".resource.spec.runtimeImageOverride"
  - type: string
    name: "namespace"
    shorthand: "n"
    description: "Function's namespace"
    configPath: ".resource.metadata.namespace"
    default: "default"
  - type: string
    name: "runtime"
    description: "function runtime"
    shorthand: "r"
    configPath: ".resource.spec.runtime"
    default: "nodejs22"
  - type: int
    name: "replicas"
    description: "function replicas"
    configPath: ".resource.spec.replicas"
    default: "1"
  - type: path
    name: "source"
    description: "function source file path"
    shorthand: "s"
    configPath: ".resource.spec.source.inline.source"
    default: |
      module.exports = {
        main: function(event, context) {
          return 'Hello World!'
        }
      }
  - type: path
    name: "dependencies"
    description: "function dependencies file path"
    shorthand: "d"
    configPath: ".resource.spec.source.inline.dependencies"

- metadata:
    name: "init [flags]"
    description: Init source and dependencies files locally
    descriptionLong: Use this command to initialize source and dependencies files for a Function.
  uses: function_init
  flags:
  - name: runtime
    configPath: ".useRuntime"
    type: string
    description: "Runtime for which the files are generated [ nodejs22, nodejs20, python312 ]"
    default: "nodejs22"
  - name: dir
    configPath: ".outputDir"
    type: string
    description: "Path to the directory where files must be created"
    default: "."
  with:
    runtimes:
      python312:
        depsFilename: requirements.txt
        depsData: ""
        handlerFilename: handler.py
        handlerData: |
          def main(event, context):
            message = "Hello World from the Kyma Function "+context['function-name']+" running on "+context['runtime']+ "!";
            print(message)
            return message
      nodejs22:
        depsFilename: package.json
        depsData: |
          {
            "dependencies": {}
          }
        handlerFilename: handler.js
        handlerData: |
          module.exports = {
            main: async function (event, context) {
              /*
              If you prefer mjs import/export syntax over cjs you need to specify
              'type': 'module'
              in the Function dependencies (package.json) and along with that change the import/export syntax to:
              import foo from 'foo'
              export function main(event, context) {
                //your logic using foo library
                return
              }
              */

              const message = `Hello World`
                + ` from the Kyma Function ${context["function-name"]}`
                + ` running on ${context.runtime}!`;
              console.log(message);
              return message;
            }
          }
      nodejs20:
        depsFilename: package.json
        depsData: |
          {
            "dependencies": {}
          }
        handlerFilename: handler.js
        handlerData: |
          module.exports = {
            main: async function (event, context) {
              /*
              If you prefer mjs import/export syntax over cjs you need to specify
              'type': 'module'
              in the Function dependencies (package.json) and along with that change the import/export syntax to:
              import foo from 'foo'
              export function main(event, context) {
                //your logic using foo library
                return
              }
              */

              const message = `Hello World`
                + ` from the Kyma Function ${context["function-name"]}`
                + ` running on ${context.runtime}!`;
              console.log(message);
              return message;
            }
          }
```

## Registry extension yaml

```yaml
metadata:
  name: registry
  description: A set of commands for the Kyma registry
  descriptionLong: Use this command to manage resources related to the Kyma registry.

subCommands:
- metadata:
    name: "config-external [flags]"
    description: "Saves Kyma registry external dockerconfig"
    descriptionLong: "Use this command to save Kyma registry external dockerconfig."
  uses: registry_config
  flags:
  - type: bool
    name: "push-reg-addr"
    description: "Get external registry push address only"
    configPath: ".pushRegAddrOnly"
    default: "false"
  - type: bool
    name: "pull-reg-addr"
    description: "Get external registry address used to pull images"
    configPath: ".pullRegAddrOnly"
    default: "false"
  - type: string
    name: "output"
    description: "Path where the output file should be saved to. NOTE: docker expects the file to be named 'config.json'"
    configPath: ".output"
  with:
    useExternal: true

- metadata:
    name: "config-internal [flags]"
    description: "Saves Kyma registry internal dockerconfig"
    descriptionLong: "Use this command to save Kyma registry internal dockerconfig."
  uses: registry_config
  flags:
  - type: bool
    name: "push-reg-addr"
    description: "Get in-cluster registry address only"
    configPath: ".pushRegAddrOnly"
    default: "false"
  - type: bool
    name: "pull-reg-addr"
    description: "Get in-cluster registry address used to pull images by Kubernetes only"
    configPath: ".pullRegAddrOnly"
    default: "false"
  - type: string
    name: "output"
    description: "Path where the output file should be saved to. NOTE: docker expects the file to be named 'config.json'"
    configPath: ".output"
  with:
    useExternal: false

- metadata:
    name: "image-import <image> [flags]"
    description: "Import image to in-cluster registry"
    descriptionLong: "Import image from daemon to in-cluster registry."
  uses: registry_image_import
  args:
    type: string
    configPath: ".image"
```
