### ISSUE TITLE
Empty requirements.txt file passed as `--dependencies` flag for python function results in invalid json format

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2511]
**Description**

When I try to create python function with empty `requirements.txt` file, the resulting `spec.source.inline.dependencies` has invalid json format

`kyma function create tst --dependencies requirements.txt --source handler.py --runtime python312 --dry-run -oyaml
`

```yaml
spec:
    source:
        inline:
            dependencies: |
                {
                  "dependencies": {}
                }
```

When the file is nonempty, the generated function manifest is ok:

```yaml
    source:
        inline:
            dependencies: |
                camel-case=1.0.1
```
