### ISSUE TITLE
Differentiate between Module CR Status and Module Installation Status

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2523]
**Description**

Currently, when listing installed modules, we only read Operator installation status by reading Kyma CR modules status (i.e. `kubectl get kymas -n kyma-system default -oyaml | yq .status`)
What we currently show represents the module operators' installation status (from KLM perspective).

What we don't display, is the actual Module CR status, which is used by module operators to communicate status about actual module installation. 

In case of managed modules, the Module CR is referenced in the Kyma CR status, so the Kyma CLI should inspect this resource `status.state` field  i.e
```yaml
...
status:
  modules:
    - channel: fast
      fqdn: kyma-project.io/module/btp-operator
      name: btp-operator
      resource:
        apiVersion: operator.kyma-project.io/v1alpha1
        kind: BtpOperator
        metadata:
          name: btpoperator
          namespace: kyma-system
``` 

In case on community modules the installation status is not present in Kyma CR.
In case of community modules CLI should inspect the `ModuleTemplate` CR of that module to resolve:
 - installation status (from the status uf the operator deployment that is mentioned as manager in module template)
 - module CR status (by reading `status.state` of the resource referenced in  `spec.data` in ModuleTemplate CR)

**Reasons**

Users should have complete information about operator installation status (was operator succesfully installed?) and the actual module status (was operator successful to install the module k8s resources? )

**Attachments**

![Image](https://github.com/user-attachments/assets/ff053db3-c31a-47a4-8e9d-7eee7a81d61a)
