### ISSUE TITLE
KUBECONFIG environment variable is ignored

### ISSUE THREAD

**Issue by solidnerd** [kyma-project/cli#258]
**Description**

As a User I want to set my `KUBECONFIG` Env var and want to use the functionality of the cli. 

I want to set this:

```bash
$ export KUBECONFIG=/Users/nmietz/develop/cc/kyma/environments/dev/k8s_kyma_cluster
```

Here is also a proof that my config works

```
kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://your-cluster.com:443
  name: cc-default-k8s-aks
contexts:
- context:
    cluster: cc-default-k8s-aks
    user: clusterUser_cc-default_cc-default-k8s-aks
  name: cc-default-k8s-aks
current-context: cc-default-k8s-aks
kind: Config
preferences: {}
users:
- name: clusterUser_cc-default_cc-default-k8s-aks
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: C2RqLiEaDZhkcmVwL86sOXMpH3Ol6SOmndR4X7Sz8C59wYHiB2yGcLpRxJqVCjokv3iEOE0DN01K1mqfXk6ENRyHhbd5RrQjzCoFcD5IGGmKofebGaa7XdkM9HAQjUAS
```

```
kubectl get pods -n kyma-installer
NAME                             READY   STATUS      RESTARTS   AGE
helm-certs-job-nh6jm             0/1     Completed   2          46h
kyma-installer-d7d7cfd96-pdddg   1/1     Running     0          46h

```

**Expected result**

```bash
$ kyma console
Reading the Kyma console URL from the cluster
Opening the Kyma console in the default browser
```

**Actual result**

```bash
$ kyma console
Reading the Kyma console URL from the cluster
Unable to read the Kyma console URL due to error: Get https://kubernetes.docker.internal:6443/apis/networking.istio.io/v1alpha3/namespaces/kyma-system/virtualservices/core-console?timeout=30s: dial tcp 127.0.0.1:6443: connect: connection refused. Check if your cluster is available and has Kyma installed
```
**Steps to reproduce**

1. `export KUBECONFIG=<valid kubeconfig file>`
2. `kyma console`

**Troubleshooting**

Copying the current config to `.kube/config` works as a workaround.

```bash
cp $HOME/.kube/confg $HOME/.kube/config.old && cp $KUBECONFIG $HOME/.kube/config
```
