### ISSUE TITLE
Override file with trailing --- will result in warning

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#352]
**Description**
I used the `kyma install -o myfile.yaml` with a config override. The yaml file contained:

````
---
apiVersion: "installer.kyma-project.io/v1alpha1"
kind: Installation
metadata:
  name: kyma-installation
  namespace: default
  labels:
    action: install
    kyma-project.io/installation: ""
  finalizers:
    - finalizer.installer.kyma-project.io
spec:
  version: "__VERSION__"
  url: "__URL__"
  components:
    - name: "cluster-essentials"
      namespace: "kyma-system"
    - name: "testing"
      namespace: "kyma-system"
````

and was throwing a warning in the initial phase:
````
- Cluster info read
- Configurations validated
  Using the installation configuration from 'master'
  Installing Kyma in version 'master-f541788a'
- Installation source checked
- Tiller deployed
- Installation files loaded
| Deploying Kyma Installer unable to retrieve the kind of config. file: myfile.yaml
- Kyma Installer deployed
- Minikube IP added
- Helm configured
- Kyma Installer is installing Kyma
````

**Expected result**

I expect no warning for the file as it describes kubernetes resources in a valid way.
For me it was not obvious that still everything got applied as expected, so maybe also make clear that one entry was not processed but still all others were fine..

**Actual result**
A warning which indicated me that the file was skipped fully

**Steps to reproduce**

**Troubleshooting**
