### ISSUE TITLE
New installation: local domain overriding user provided domain

### ISSUE THREAD

**Issue by colunira** [kyma-project/cli#749]
**Description**

I was trying to install Kyma with `kyma alpha deploy` with my own domain, but I provided it as an override, not with the `--domain` flag. Kyma was installed with `local.kyma.dev` domain.

**Expected result**

Kyma is installed with my domain.

**Actual result**

Kyma was installed with the domain `local.kyma.dev`.

**Steps to reproduce**

Create file with overrides:
```
global:
  domainName: my.domain.com
  ingress: 
    domainName: my.domain.com
```
Run `kyma alpha deploy -f file.yaml

**Troubleshooting**

**Comment by JeremyHarisch** [comment]
This issue has already been fixed.

I tested two cases:

1. `kyma alpha deploy -d my.domain.com`
```
Kyma is installed in version:	main
Kyma installation took:		0 hours 6 minutes
Kyma is running at:		my.domain.com
Kyma console:			not installed
```
2. `kyma alpha deploy -f customDomain.yaml`
```
Kyma is installed in version:	main
Kyma installation took:		0 hours 5 minutes
Kyma is running at:		my.domain.com
Kyma console:			not installed
```
Content of customDomain.yaml:
```
global:
  domainName: my.domain.com
  ingress: 
    domainName: my.domain.com
```
