### ISSUE TITLE
Allow exposing functions via kyma CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#771]
**Description**

As a CLI user I want to expose my function so that it is accessible via HTTP
 - [x] Allow to define api rules as part of function manifest ( config.yaml )
 - [x] The API rule spec should allow for `allow` and `jwt` access strategies
 - [x] API rules should be deployed in the runtime after `apply` command
 - [x] API rules should be read from the runtime and written to the manifest file after `sync` comannd
 - [ ] STRETCH add a new `expose` command that would modify the manifest file

**Reasons**
ATM it's not possible to expose function via kyma CLI
Users have to add api rules via  console UI or kubectl.

**Comment by kwiatekus** [comment]
```yaml
name: my-function
namespace: my-namespace
runtime: nodejs12
source:
    sourceType: inline
    sourcePath: ...
triggers:
    - version: v1
      source: ec-mock
      type: order.deliverysent
apirules:
      .........      
  ```
