### ISSUE TITLE
Improve defaulting of sourcePath in the function config

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/cli#828]
**Description**

Now, output from the `kyma init function` looks like this:
```
workspaceVersion: ""
name: function-sharp-karolina9
namespace: default
runtime: nodejs12
source:
    sourceType: inline
    sourcePath: /tmp/tmp
```
We don't need to always show user property `source.sourcePath` because it's always `$PWD` by default. We can change it to `.` or just remove it from generated config. In the second option, the user can always override the default `sourcePath` by adding it to the config, but the default value for this property should be a folder where `config.yaml` exists. 

My proposition:
- Remove `source.sourcePath` from the config template by default
- Default value (if there is no value for `source.sourcePath` in the `config.yaml`) is folder where the `config.yaml` exists
- User can override this value by adding a custom path (to the `source.sourcePath`)

**Reasons**

Better user experience. Why is the default value for this field in the config? I think that the user doesn't need to understand how kymaCli apply resources to the cluster and he doesn't need to see default values in config which can be confusing for him. But he still should be possible to set his own value, for example, if he locates the code of his functions in another folder than config.
