### ISSUE TITLE
Fix subscription generation in function CLI

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/cli#938]
**Description**

`Subscription` CR generated by function Kyma CLI should have `protocolsettings` property omitted if it is not overriden by user.   

**Expected result**

**Actual result**

```
...
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce.order.created.v1
  protocolsettings:
    exemptHandshake: true
    qos: AT-LEAST-ONCE
    webhookAuth:
      clientId: ""
      clientSecret: ""
      grantType: ""
      tokenUrl: ""
  sink: http://function-quirky-karolina6.test.svc.cluster.local
```

```
...
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce.order.created.v1
  sink: http://function-quirky-karolina6.test.svc.cluster.local
```

**Steps to reproduce**

Apply function with the following project configuration:

```
name: function-quirky-karolina6
namespace: testing
runtime: nodejs14
source:
    sourceType: inline
subscriptions:
    - name: function-practical-filip5
      protocol: ""
      filter:
        dialect: ""
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: test

``` 

**Troubleshooting**
