### ISSUE TITLE
Fix API Rule synchronisation

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/cli#939]
**Description**

Fix API Rule synchronisation. 

**Expected result**

CLI should synchronise API rules.

**Actual result**

CLI does not synchronise API Rules and duplicates them in function namespace.

**Steps to reproduce**

1. Configure kyma to work with EMS.
2. Create function `kyma init function`.
3. Add EMS Subscription:
```
subscriptions:
    - name: ems-fs-function
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.order.created.v1
```
4. Apply function `kyma apply function`.
5. Synchronise function `kyma sync function`.
6. List API rules from function namespace.

**Troubleshooting**
