### ISSUE TITLE
As a user I want to be able to synchronise only Subscriptions from the function's namespace

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/cli#941]
**Description**

As a user I want to be able synchronise only Subscriptions from the function's namespace.
- Function project synchronisation does not work as expected

**Expected result**

```yaml
name: ce-coffee
namespace: ce-coffee
runtime: nodejs14
source:
    sourceType: inline
    sourcePath: /Users/i517616/go/src/github.com/pPrecel/fass2kyma
subscriptions:
    - name: ce-coffee
      namespace: testing
      ...
    - name: ce-coffee
      namespace: testing123
      ...
```

**Actual result**

```yaml
name: ce-coffee
namespace: ce-coffee
runtime: nodejs14
source:
    sourceType: inline
    sourcePath: /Users/i517616/go/src/github.com/pPrecel/fass2kyma
subscriptions:
    - name: ce-coffee
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.coffee.produced.aaa
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.coffee.consumed.aaxcas
    - name: ce-coffee
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.order.created.v1
```

**Steps to reproduce**

1. Create function with subscription in namespace A
2. Create subscription in namespace B
3. Synchronise function project `kyma sync function`

**Troubleshooting**
